version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=igor
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nicecode
    ports:
      - "5432:5432"
  web:

    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ./.env.dev 
    container_name: web
    

volumes:
  postgres_volume:
