# Generated by Django 4.1.7 on 2023-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Склады', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='products_in_use',
            field=models.ManyToManyField(through='core.ClientProduct', to='core.product', verbose_name='Товары, которые нужно разместить'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название склада'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='products',
            field=models.ManyToManyField(through='core.WarehouseProduct', to='core.product', verbose_name='Названия товаров, доступных к размещению'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='storage_limit',
            field=models.IntegerField(default=0, verbose_name='Общий лимит товаров к размещению(шт.)'),
        ),
    ]
